# Generated by Django 3.2 on 2021-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='extra_stuff_notes',
            field=models.TextField(default=''),
        ),
    ]
