# Generated by Django 3.2 on 2021-05-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_is_order_placed'),
        ('billing', '0002_alter_billing_extra_stuff_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.address'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart'),
        ),
    ]
