# Generated by Django 3.2 on 2021-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210510_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
