# Generated by Django 3.2 on 2021-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], max_length=10)),
                ('desc', models.CharField(max_length=30)),
                ('isNew', models.BooleanField()),
                ('isInOffer', models.BooleanField()),
                ('discount', models.CharField(max_length=10)),
                ('oldPrice', models.IntegerField(default=0)),
                ('newPrice', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='media/')),
                ('isInTopSale', models.BooleanField(default=False)),
                ('extraStuff', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
