# Generated by Django 3.2 on 2021-05-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='extraStuff',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoes',
            name='desc',
            field=models.CharField(max_length=30),
        ),
    ]
