# Generated by Django 3.2 on 2021-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210507_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Kids', max_length=10),
            preserve_default=False,
        ),
    ]
