# Generated by Django 3.2 on 2021-05-08 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_productcart_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.IntegerField(default=0)),
                ('productCart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.productcart')),
            ],
        ),
    ]
