# Generated by Django 3.2 on 2021-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210508_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='newPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='oldPrice',
            field=models.IntegerField(default=0),
        ),
    ]
