# Generated by Django 3.2 on 2021-05-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210508_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='size',
            field=models.CharField(default=4, max_length=5),
        ),
    ]
