# Generated by Django 3.2 on 2021-05-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_productcart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shoes'),
        ),
    ]
