# Generated by Django 3.2 on 2021-05-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210508_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcart',
            options={'ordering': ['product_id']},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ['name']},
        ),
    ]
