# Generated by Django 3.2 on 2021-05-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210509_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
