# Generated by Django 3.2 on 2021-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210509_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
