# Generated by Django 3.2 on 2021-05-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
