# Generated by Django 3.2 on 2021-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_productcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products_list',
            field=models.JSONField(default=''),
        ),
    ]
