# Generated by Django 3.2 on 2021-05-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_products_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
